import os
import numpy as np
from astropy.io import fits
import makecutouts

def makeinspectionsite(object,field,prefix='/Users/carletont/halo7d',fileprefix='inspectionsite_',relativedir='../cutouts'):
    cutouts=os.listdir(prefix+'/cutouts/')

    webfile=open(prefix+'/'+fileprefix+str(object)+'.html','w') #"inspectionsite_1sig.html is the name of the website
    if str(object) not in cutouts:
        makecutouts.makecutouts(object,savedir=prefix+'/cutouts/',field=field)

    objcutouts=os.listdir(prefix+'/cutouts/'+str(object)+'/')

    objbase=[objcutouts[i][objcutouts[i].find('_')+1:] for i in range(len(objcutouts))]

    bounds=np.loadtxt(prefix+'/cutouts/'+str(object)+'/bounds.txt')
    nsmooth=int((len(bounds)-3)/3)

    noise=np.loadtxt(prefix+'/cutouts/'+str(object)+'/noise.txt')
    zbest=np.loadtxt(prefix+'/cutouts/'+str(object)+'/zbest.txt')
    
    webfile.write('<!DOCTYPE html>\n')
    webfile.write('<html>\n')
    webfile.write('<head>\n')
    webfile.write('<title>Clump Inspection for HALO7D objects</title>\n')

    webfile.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>\n')
    webfile.write('<style>\n')
    webfile.write('#container {\n')
    webfile.write('\tposition:relative;\n')
    webfile.write('\tpadding:0px;\n')
    webfile.write('}\n')

    webfile.write('#imgdot {\n')
    webfile.write('\tposition: relative;\n')
    webfile.write('}\n')
    webfile.write('</style>\n')
    webfile.write('\n')
    webfile.write('<script>\n')
    
    webfile.write('$(document).ready(function(){\n')
    #webfile.write('\t$("img.img").mousemove(function(event) {\n')
    webfile.write('\t$(".img").mousemove(function(event) {\n')
    webfile.write('\tvar X=event.pageX-this.getBoundingClientRect().left-pageXOffset;\n')
    webfile.write('\tvar Y=event.pageY-this.getBoundingClientRect().top-pageYOffset;\n')
    webfile.write('\tvar width=this.getBoundingClientRect().right-this.getBoundingClientRect().left;\n')
    webfile.write('\tvar height=this.getBoundingClientRect().bottom-this.getBoundingClientRect().top;\n')

    webfile.write('\tif (this.id[3]=="c") {\n')
    webfile.write('\t\tif(X/width>'+str(bounds[0][0])+' && X/width<'+str(bounds[0][0]+bounds[0][2])+' && Y/height>'+str(1-(bounds[0][1]+bounds[0][3]))+' && Y/height<'+str(1-(bounds[nsmooth][1]))+') {\n')
    webfile.write('\t\t\tif(Y/height>'+str(1-(bounds[0][1]+bounds[0][3]))+' && Y/height<'+str(1-(bounds[0][1]))+') {\n')
    webfile.write('\t\t\t\tvar axy=((1-Y/height)-'+str(bounds[0][1])+')/'+str(bounds[0][3])+'*'+str(bounds[0][7])+'+'+str(bounds[0][5])+';\n')
    for sm in range(1,nsmooth):
        webfile.write('\t\t\t} else if(Y/height>'+str(1-(bounds[sm][1]+bounds[sm][3]))+' && Y/height<'+str(1-(bounds[sm][1]))+') {\n')
        webfile.write('\t\t\t\tvar axy=((1-Y/height)-'+str(bounds[sm][1])+')/'+str(bounds[sm][3])+'*'+str(bounds[sm][7])+'+'+str(bounds[sm][5])+';\n')
        
    webfile.write('\t\t\t} else {\n')
    webfile.write('\t\t\t\tvar axy=((1-Y/height)-'+str(bounds[nsmooth][1])+')/'+str(bounds[nsmooth][3])+'*'+str(bounds[nsmooth][7])+'+'+str(bounds[nsmooth][5])+';\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\t\tvar axx=(X/width-'+str(bounds[0][0])+')/'+str(bounds[0][2])+'*'+str(bounds[0][6])+'+'+str(bounds[0][4])+';\n')
    
    webfile.write('\t\t\t$("td#pos"+this.id.substring(3)).html("X:"+axx.toFixed(2)+"<br>Y:"+axy.toFixed(2));\n')
    webfile.write('\t\t}\n')
    
    webfile.write('\t} else if (this.id[3]=="1"){\n')
    webfile.write('\t\tif(Y/height>'+str(1-(bounds[nsmooth+1][1]+bounds[nsmooth+1][3]))+' && Y/height<'+str(1-(bounds[nsmooth+1][1]))+') {\n')
    webfile.write('\t\t\tvar axy=((1-Y/height)-'+str(bounds[nsmooth+1][1])+')/'+str(bounds[nsmooth+1][3])+'*'+str(bounds[nsmooth+1][7])+'+'+str(bounds[nsmooth+1][5])+';\n')
    for sm in range(2,2*nsmooth-2,2):
        webfile.write('\t\t} else if(Y/height>'+str(1-(bounds[nsmooth+1+sm][1]+bounds[nsmooth+1+sm][3]))+' && Y/height<'+str(1-(bounds[nsmooth+1+sm][1]))+') {\n')
        webfile.write('\t\t\tvar axy=((1-Y/height)-'+str(bounds[nsmooth+1+sm][1])+')/'+str(bounds[nsmooth+1+sm][3])+'*'+str(bounds[nsmooth+1+sm][7])+'+'+str(bounds[nsmooth+1+sm][5])+';\n')
        
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\tvar axy=((1-Y/height)-'+str(bounds[nsmooth+1+nsmooth+2][1])+')/'+str(bounds[nsmooth+1+nsmooth+2][3])+'*'+str(bounds[nsmooth+1+nsmooth+2][7])+'+'+str(bounds[nsmooth+1+nsmooth+2][5])+';\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\tif(X/width>'+str(bounds[nsmooth+1][0])+' && X/width<'+str(bounds[nsmooth+1][0]+bounds[nsmooth+1][2])+') {\n')
    webfile.write('\t\t\tvar axx=(X/width-'+str(bounds[nsmooth+1][0])+')/'+str(bounds[nsmooth+1][2])+'*'+str(bounds[nsmooth+1][6])+'+'+str(bounds[nsmooth+1][4])+';\n')
    webfile.write('\t\t\tvar imgobj=this.id.substring(5);\n')

    webfile.write('\t\t} else if(X/width>'+str(bounds[nsmooth+2][0])+' && X/width<'+str(bounds[nsmooth+2][0]+bounds[nsmooth+2][2])+') {\n')
    webfile.write('\t\t\tvar axx=(X/width-'+str(bounds[nsmooth+2][0])+')/'+str(bounds[nsmooth+2][2])+'*'+str(bounds[nsmooth+2][6])+'+'+str(bounds[nsmooth+2][4])+';\n')
    webfile.write('\t\t\tvar imgobj=this.id.substring(5);\n')
    webfile.write('\t}\n')
    webfile.write('\tif(X/width>'+str(bounds[nsmooth+1][0])+' && X/width<'+str(bounds[nsmooth+2][0]+bounds[nsmooth+2][2]) +' && Y/height>'+str(1-(bounds[nsmooth+1][1]+bounds[nsmooth+1][3]))+' && Y/height<'+str(1-(bounds[nsmooth+1+nsmooth+2][1]))+') {\n')
    webfile.write('\t\t$("td#pos"+imgobj).html("X:"+axx.toFixed(2)+"<br>Y:"+axy.toFixed(2));\n')
    webfile.write('\t}\n')

    webfile.write('\t} else if (this.id[3]=="2"){\n')
    webfile.write('\t\t if(X/width>'+str(bounds[-2][0])+' && X/width<'+str(bounds[-2][0]+bounds[-2][2])+' && Y/height>'+str(bounds[-2][1])+' && Y/height<'+str(bounds[-2][1]+bounds[-2][3])+') {\n')
    webfile.write('\t\t\tvar axxwav=(X/width-'+str(bounds[-2][0])+')/'+str(bounds[-2][2])+'*'+str(bounds[-4][6])+'+'+str(bounds[-4][4])+';\n')
    webfile.write('\t\t\tvar axxpix=(X/width-'+str(bounds[-2][0])+')/'+str(bounds[-2][2])+'*'+str(bounds[-2][6])+'+'+str(bounds[-2][4])+';\n')
    webfile.write('\t\t\tvar axy=(Y/height-'+str(bounds[-2][1])+')/'+str(bounds[-2][3])+'*'+str(-bounds[-2][7])+'+'+str(bounds[-2][5]+bounds[-2][7])+';\n')
    webfile.write('\t\t\tvar imgobj=this.id.substring(5);\n')
    webfile.write('\t\t\t$("td#pos"+imgobj).html("Wave: "+axxwav.toFixed(2)+"<br>Y:"+axy.toFixed(2)+"<br>Pix: "+axxpix.toFixed(2));\n')
    webfile.write('\t\t} else if(X/width>'+str(bounds[-1][0])+' && X/width<'+str(bounds[-1][0]+bounds[-1][2])+' && Y/height>'+str(bounds[-1][1])+' && Y/height<'+str(bounds[-1][1]+bounds[-1][3])+') {\n')
    webfile.write('\t\t\tvar axxwav=(X/width-'+str(bounds[-1][0])+')/'+str(bounds[-1][2])+'*'+str(bounds[-3][6])+'+'+str(bounds[-3][4])+';\n')
    webfile.write('\t\t\tvar axxpix=(X/width-'+str(bounds[-1][0])+')/'+str(bounds[-1][2])+'*'+str(bounds[-1][6])+'+'+str(bounds[-1][4])+';\n')
    webfile.write('\t\t\tvar axy=(Y/height-'+str(bounds[-1][1])+')/'+str(bounds[-1][3])+'*'+str(-bounds[-1][7])+'+'+str(bounds[-1][5]+bounds[-2][7])+';\n')
    webfile.write('\t\t\tvar imgobj=this.id.substring(5);\n')
    webfile.write('\t\t\t$("td#pos"+imgobj).html("Wave: "+axxwav.toFixed(2)+"<br>Y:"+axy.toFixed(2)+"<br>Pix: "+axxpix.toFixed(0));\n')
    webfile.write('\t}\n')
    webfile.write('\t}\n')
    webfile.write('\t});\n')
    webfile.write('});\n')
    webfile.write('</script>\n')

    webfile.write('<script>\n')
    webfile.write('function deleteLine(img) {\n')
    webfile.write('\tvar tosel=img.getAttribute("data-tosel");\n')
    webfile.write('\tvar wave=img.getAttribute("data-wave");\n')
    webfile.write('\tif(tosel==0) {\n')
    webfile.write('\t\talter=document.getElementById("strongemlines");\n')
    webfile.write('\t\talternum=document.getElementById("numstrongemlines");\n')
    webfile.write('\t} else if(tosel==1) {\n')
    webfile.write('\t\talter=document.getElementById("weakemlines");\n')
    webfile.write('\t\talternum=document.getElementById("numweakemlines");\n')
    webfile.write('\t} else if(tosel==2) {\n')
    webfile.write('\t\talter=document.getElementById("strongabslines");\n')
    webfile.write('\t\talternum=document.getElementById("numstrongabslines");\n')
    webfile.write('\t} else {\n')
    webfile.write('\t\talter=document.getElementById("weakabslines");\n')
    webfile.write('\t\talternum=document.getElementById("numweakabslines");\n')
    webfile.write('\t}\n')
    webfile.write('\tif(alternum.selectedIndex==0) {\n')
    webfile.write('\t\talert("ERROR")\n')
    webfile.write('\t} else {\n')
    webfile.write('\t\tvar waves=alter.value.split("\\n")\n')
    webfile.write('\t\tvar wavestosave=[];\n')
    webfile.write('\t\tfor(var i=0;i<waves.length;i++) {\n')
    webfile.write('\t\t\tif(waves[i]!=wave) {\n')
    webfile.write('\t\t\t\twavestosave.push(waves[i]);\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t}\n')
    webfile.write('\t}\n')
    webfile.write('\talter.value=wavestosave.join("\\n");\n')
    webfile.write('\tif(waves.length-1>=4) {\n')
    webfile.write('\t\talternum.selectedIndex=4;\n')
    webfile.write('\t\talter.setAttribute("rows",4);\n')
    webfile.write('\t} else {\n')
    webfile.write('\t\talternum.selectedIndex=waves.length-1;\n')
    webfile.write('\t\tif(waves.length-1==0) {\n')
    webfile.write('\t\t\talter.setAttribute("rows",1);\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\talter.setAttribute("rows",waves.length-1);\n')
    webfile.write('\t\t}\n')
    webfile.write('\t}\n')
    webfile.write('}\n')
    webfile.write('</script>\n')

    webfile.write('<script>\n')
    webfile.write('function addLine(wave,tosel) {\n')
    webfile.write('\t\tif(tosel==0) {\n')
    webfile.write('\t\t\talter=document.getElementById("strongemlines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numstrongemlines");\n')
    webfile.write('\t\t} else if(tosel==1) {\n')
    webfile.write('\t\t\talter=document.getElementById("weakemlines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numweakemlines");\n')
    webfile.write('\t\t} else if(tosel==2) {\n')
    webfile.write('\t\t\talter=document.getElementById("strongabslines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numstrongabslines");\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\talter=document.getElementById("weakabslines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numweakabslines");\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\tvar waves=alter.value.split("\\n")\n')
    webfile.write('\t\tif(alternum.selectedIndex==0) {\n')
    webfile.write('\t\t\talter.setAttribute("rows",1);\n')
    webfile.write('\t\t\talternum.selectedIndex=1;\n')
    webfile.write('\t\t\tvar wavestosave=alter.value+wave;\n')
    webfile.write('\t\t} else if(alternum.selectedIndex<3) {\n')
    webfile.write('\t\t\talter.setAttribute("rows",alternum.selectedIndex+1);\n')
    webfile.write('\t\t\talternum.selectedIndex=alternum.selectedIndex+1;\n')
    webfile.write('\t\t\tvar wavestosave=alter.value+"\\n"+wave;\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\talter.setAttribute("rows",4);\n')
    webfile.write('\t\t\talternum.selectedIndex=4;\n')
    webfile.write('\t\t\tvar wavestosave=alter.value+"\\n"+wave;\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\talter.value=wavestosave;\n')
   
    webfile.write('}\n')
    webfile.write('</script>\n')

    webfile.write('<script>\n')
    webfile.write('function changeType(img,newtype) {\n')
    #webfile.write('\taddLine(img.getAttribute("data-wave"),img.getAttribute("data-tosel"));\n')
    webfile.write('\tvar oldtype=img.getAttribute("data-tosel");\n')
    webfile.write('\taddLine(img.getAttribute("data-wave"),newtype);\n')
    webfile.write('\tdeleteLine(img);\n')
    webfile.write('\timg.setAttribute("data-tosel",newtype);\n')
    webfile.write('\tif(newtype==0) {\n')
    webfile.write('\t\timg.style.width="20px";\n')
    webfile.write('\t\timg.setAttribute("src","redmarker.png");\n')
    webfile.write('\t\tif(oldtype==1 || oldtype==3) {\n')
    webfile.write('\t\t\timg.style.left=(img.offsetLeft-5)+"px";\n')
    webfile.write('\t\t\timg.style.top=(img.offsetTop-5)+"px";\n')
    #webfile.write('\t\t\talert("X");\n')
    webfile.write('\t\t}\n')
    webfile.write('\t} else if(newtype==1) {\n')
    webfile.write('\t\timg.style.width="10px";\n')
    webfile.write('\t\tif(oldtype==0 || oldtype==2) {\n')
    webfile.write('\t\t\timg.style.left=(img.offsetLeft+5)+"px";\n')
    webfile.write('\t\t\timg.style.top=(img.offsetTop+5)+"px";\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\timg.setAttribute("src","redmarker.png");\n')
    webfile.write('\t} else if(newtype==2) {\n')
    webfile.write('\t\timg.style.width="20px";\n')
    webfile.write('\t\timg.setAttribute("src","bluemarker.png");\n')
    webfile.write('\t\tif(oldtype==1 || oldtype==3) {\n')
    webfile.write('\t\t\timg.style.left=(img.offsetLeft-5)+"px";\n')
    webfile.write('\t\t\timg.style.top=(img.offsetTop-5)+"px";\n')
    webfile.write('\t\t}\n')
    webfile.write('\t} else {\n')
    webfile.write('\t\timg.style.width="10px";\n')
    webfile.write('\t\timg.setAttribute("src","bluemarker.png");\n')
    webfile.write('\t\tif(oldtype==0 || oldtype==2) {\n')
    webfile.write('\t\t\timg.style.left=(img.offsetLeft+5)+"px";\n')
    webfile.write('\t\t\timg.style.top=(img.offsetTop+5)+"px";\n')
    webfile.write('\t\t}\n')
    webfile.write('\t}\n')
    #webfile.write('\t\talert(orig);\n')
    #webfile.write('\t\talert(new);\n')
    
    webfile.write('}\n')
    webfile.write('</script>\n')
    

    webfile.write('<script>\n')
    webfile.write('function pointClick(img) {\n')
    webfile.write('\ttoadd=document.getElementById("container");\n')
    webfile.write('\tvar sel=document.createElement("table");\n')
    webfile.write('\tsel.id="selectid";\n')
    webfile.write('\tvar tosel=img.getAttribute("data-tosel");\n')
    webfile.write('\tvar label11 = document.createElement("label");\n')

    webfile.write('\tvar tr1 = document.createElement("tr");\n')
    
    webfile.write('\tvar td11 = document.createElement("td");\n')
    webfile.write('\tvar label11 = document.createElement("label");\n')
    webfile.write('\tvar tdr11=document.createElement("input");\n')
    webfile.write('\ttdr11.setAttribute("type","radio");\n')
    webfile.write('\ttdr11.style.height=".5em";\n')
    webfile.write('\ttdr11.style.verticalAlign= "50%";\n')
    webfile.write('\ttdr11.name="selectline1";\n')
    webfile.write('\tif(tosel==0) {\n')
    webfile.write('\t\ttdr11.checked="checked";\n')
    webfile.write('\t}\n')
    webfile.write('\ttdr11.onchange=function() {changeType(img,0);};\n')
    webfile.write('\tlabel11.innerHTML += "Strong Em";\n')
    webfile.write('\ttd11.appendChild(tdr11);\n')
    webfile.write('\ttd11.appendChild(label11);\n')

    webfile.write('\tvar td12 = document.createElement("td");\n')
    webfile.write('\tvar label12 = document.createElement("label");\n')
    webfile.write('\tvar tdr12=document.createElement("input");\n')
    webfile.write('\ttdr12.setAttribute("type","radio");\n')
    webfile.write('\ttdr12.style.height=".5em";\n')
    webfile.write('\ttdr12.style.verticalAlign= "50%";\n')
    webfile.write('\ttdr12.name="selectline1";\n')
    webfile.write('\tif(tosel==1) {\n')
    webfile.write('\t\ttdr12.checked="checked";\n')
    webfile.write('\t}\n')
    webfile.write('\ttdr12.onchange=function() {changeType(img,1);};\n')
    webfile.write('\tlabel12.innerHTML += "Weak Em";\n')
    webfile.write('\ttd12.appendChild(tdr12);\n')
    webfile.write('\ttd12.appendChild(label12);\n')

    webfile.write('\ttr1.appendChild(td11);\n')
    webfile.write('\ttr1.appendChild(td12);\n')

    
    webfile.write('\tvar tr2 = document.createElement("tr");\n')
    
    webfile.write('\tvar td21 = document.createElement("td");\n')
    webfile.write('\tvar label21 = document.createElement("label");\n')
    webfile.write('\tvar tdr21=document.createElement("input");\n')
    webfile.write('\ttdr21.setAttribute("type","radio");\n')
    webfile.write('\ttdr21.style.height=".5em";\n')
    webfile.write('\ttdr21.style.verticalAlign= "50%";\n')
    webfile.write('\ttdr21.name="selectline1";\n')
    webfile.write('\tif(tosel==2) {\n')
    webfile.write('\t\ttdr21.checked="checked";\n')
    webfile.write('\t}\n')
    webfile.write('\ttdr21.onchange=function() {changeType(img,2);};\n')
    webfile.write('\tlabel21.innerHTML += "Strong Abs";\n')
    webfile.write('\ttd21.appendChild(tdr21);\n')
    webfile.write('\ttd21.appendChild(label21);\n')

    webfile.write('\tvar td22 = document.createElement("td");\n')
    webfile.write('\tvar label22 = document.createElement("label");\n')
    webfile.write('\tvar tdr22=document.createElement("input");\n')
    webfile.write('\ttdr22.setAttribute("type","radio");\n')
    webfile.write('\ttdr22.style.height=".5em";\n')
    webfile.write('\ttdr22.style.verticalAlign= "50%";\n')
    webfile.write('\ttdr22.name="selectline1";\n')
    webfile.write('\tif(tosel==3) {\n')
    webfile.write('\t\ttdr22.checked="checked";\n')
    webfile.write('\t}\n')
    webfile.write('\ttdr22.onchange=function() {changeType(img,3);};\n')
    webfile.write('\tlabel22.innerHTML += "Weak Abs";\n')
    webfile.write('\ttd22.appendChild(tdr22);\n')
    webfile.write('\ttd22.appendChild(label22);\n')

    webfile.write('\ttr2.appendChild(td21);\n')
    webfile.write('\ttr2.appendChild(td22);\n')
    

    webfile.write('\tsel.appendChild(tr1);\n')
    webfile.write('\tsel.appendChild(tr2);\n')
    webfile.write('\tsel.style.position="absolute";\n')
    webfile.write('\tsel.style.top=img.style.top;\n')
    webfile.write('\tsel.style.left=img.style.left;\n')
    webfile.write('\ttoadd.appendChild(sel);\n')
    webfile.write('\twindow.onkeydown=function(event) {\n')
    webfile.write('\tif(event.key=="Delete" || event.key=="Backspace") {\n')
    webfile.write('\t\tdeleteLine(img);\n')
    webfile.write('\t\ttoadd.removeChild(sel);\n')
    webfile.write('\t\tcanv=document.getElementById("container");\n')
    webfile.write('\t\tcanv.removeChild(img);\n')
    webfile.write('\t}\n')
    webfile.write('\t};\n')
    webfile.write('}\n')
    webfile.write('</script>\n')

    webfile.write('<script>\n')
    webfile.write('function onCoaddClick(event) {\n')
    webfile.write('\tif($("[id^=selectid]").length==0) {\n')
    webfile.write('\t\tvar X=event.pageX-(document.getElementById("imgc")).getBoundingClientRect().left-pageXOffset;\n')
    webfile.write('\t\tvar Y=event.pageY-(document.getElementById("imgc")).getBoundingClientRect().top-pageYOffset;\n')
    webfile.write('\t\tvar width= (document.getElementById("imgc")).getBoundingClientRect().right-(document.getElementById("imgc")).getBoundingClientRect().left;\n')
    webfile.write('\t\tvar height=(document.getElementById("imgc")).getBoundingClientRect().bottom-(document.getElementById("imgc")).getBoundingClientRect().top;\n')
    webfile.write('\t\tif(Y/height>'+str(1-(bounds[0][1]+bounds[0][3]))+' && Y/height<'+str(1-(bounds[0][1]))+') {\n')
    webfile.write('\t\t\tvar axy=((1-Y/height)-'+str(bounds[0][1])+')/'+str(bounds[0][3])+'*'+str(bounds[0][7])+'+'+str(bounds[0][5])+';\n')
    for sm in range(1,nsmooth):
        webfile.write('\t\t} else if(Y/height>'+str(1-(bounds[sm][1]+bounds[sm][3]))+' && Y/height<'+str(1-(bounds[sm][1]))+') {\n')
        webfile.write('\t\t\tvar axy=((1-Y/height)-'+str(bounds[sm][1])+')/'+str(bounds[sm][3])+'*'+str(bounds[sm][7])+'+'+str(bounds[sm][5])+';\n')
        
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\tvar axy=((1-Y/height)-'+str(bounds[nsmooth][1])+')/'+str(bounds[nsmooth][3])+'*'+str(bounds[nsmooth][7])+'+'+str(bounds[nsmooth][5])+';\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\tvar axx=(X/width-'+str(bounds[0][0])+')/'+str(bounds[0][2])+'*'+str(bounds[0][6])+'+'+str(bounds[0][4])+';\n')
    
    webfile.write('\t\ttoadd=document.getElementById("container");\n')
    webfile.write('\t\tvar img=document.createElement("img");\n')
    webfile.write('\t\tif(axy>3*'+str(noise)+') {\n')
    webfile.write('\t\t\timg.src="redmarker.png";\n')
    webfile.write('\t\t\tvar size=20;\n')
    webfile.write('\t\t\tvar tosel=0;\n')
    webfile.write('\t\t\talter=document.getElementById("strongemlines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numstrongemlines");\n')
    webfile.write('\t\t} else if(axy>0) {\n')
    webfile.write('\t\t\timg.src="redmarker.png";\n')
    webfile.write('\t\t\tvar size=10;\n')
    webfile.write('\t\t\tvar tosel=1;\n')
    webfile.write('\t\t\talter=document.getElementById("weakemlines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numweakemlines");\n')
    webfile.write('\t\t} else if(axy>-3*'+str(noise)+') {\n')
    webfile.write('\t\t\timg.src="bluemarker.png";\n')
    webfile.write('\t\t\tvar size=10;\n')
    webfile.write('\t\t\tvar tosel=3;\n')
    webfile.write('\t\t\talter=document.getElementById("weakabslines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numweakabslines");\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\timg.src="bluemarker.png";\n')
    webfile.write('\t\t\tvar size=20;\n')
    webfile.write('\t\t\tvar tosel=2;\n')
    webfile.write('\t\t\talter=document.getElementById("strongabslines");\n')
    webfile.write('\t\t\talternum=document.getElementById("numstrongabslines");\n')
    webfile.write('\t\t}\n')

    webfile.write('\t\timg.id="marker1";\n')
    webfile.write('\t\timg.setAttribute("data-tosel",tosel);\n')
    webfile.write('\t\timg.setAttribute("data-wave",axx.toFixed(2));\n')
    webfile.write('\t\timg.onclick = function() {pointClick(this);};\n')



    webfile.write('\t\timg.style.position="absolute";\n')
    webfile.write('\t\timg.style.left=(X+((document.getElementById("imgc")).getBoundingClientRect().left)-toadd.getBoundingClientRect().left-size/2)+"px";\n')
    webfile.write('\t\timg.style.top=(Y+((document.getElementById("imgc")).getBoundingClientRect().top)-toadd.getBoundingClientRect().top-size/2)+"px";\n')
    webfile.write('\t\timg.style.width=size+"px";\n')
    webfile.write('\t\ttoadd.appendChild(img);\n')

    webfile.write('\t\tif(alternum.selectedIndex==0) {\n')
    webfile.write('\t\t\talter.value+=axx.toFixed(2);\n')
    webfile.write('\t\t\talternum.selectedIndex=1;\n')
    webfile.write('\t\t} else if(alternum.selectedIndex!=4) {\n')
    webfile.write('\t\t\talter.value+="\\n"+axx.toFixed(2);\n')
    webfile.write('\t\t\talternum.selectedIndex+=1;\n')
    webfile.write('\t\t\talter.setAttribute("rows", alternum.selectedIndex);\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\talter.value+="\\n"+axx.toFixed(2);\n')
    webfile.write('\t\t}\n')
    webfile.write('\t} else {\n')
    webfile.write('\t\tselects=document.getElementById("selectid")\n')
    webfile.write('\t\ttodel=document.getElementById("container");\n')
    webfile.write('\t\ttodel.removeChild(selects);\n')
    webfile.write('\t\twindow.onkeydown=function() {};\n')
    webfile.write('\t}\n')
    webfile.write('}\n')
    webfile.write('</script>\n')
    
    webfile.write('<script>\n')
    webfile.write('\tfunction changeLines(currentElement) {\n')
    webfile.write('\tvar nlines = currentElement.value;\n')
    webfile.write('\tvar ntoshow = nlines[nlines.length-1];\n')
    webfile.write('\tif(ntoshow=="0") {\n')
    webfile.write('\t\tntoshow="1";\n')
    webfile.write('\t}\n')
    webfile.write('\t $("#"+currentElement.id.substring(3)).attr("rows",ntoshow);\n')
    
    webfile.write('}\n')
    webfile.write('</script>\n')

    webfile.write('</head>\n')
    webfile.write('<body>\n')
    webfile.write('Inspector: <input style="vertical-align: text-top" id="inspectname" style="font-size:30px">')
    webfile.write('<h2 style="font-size:22px;text-align:center; color:red">Reminder: Lighter-> more flux (+ values), darker-> less flux (- values); Non-detection is not an issue</h2>\n')
    webfile.write('<h2 style="font-size:18px;text-align:center; color:red">For each exposure, ask yourself whether its issues significantly affect the signal of the object in the extraction window (between the green lines).<br>If so, choose Major Issue; otherwise, choose Minor Issue<br></h2>\n')
    webfile.write('<h2 style="font-size:18px;text-align:center"><a href=../example_issues.html>Example Issues</a></h2>\n')
    webfile.write('<h1 style="font-size:50px;text-align:center">Object '+str(object)+'</h1>\n')
    #webfile.write('Load a previously saved file:<input type="file" id="fileToLoad"><button onclick="loadFileAsText()">Load Selected File</button>\n')
    #webfile.write('<table style="width:100%" align="center">\n')
    webfile.write('<table>\n')
    webfile.write('\t<tr>\n')
    webfile.write('\t\t<th style="font-size:30px">Spectra</th>\n')
    webfile.write('\t\t<th style="font-size:30px;width:10ch;text-align:left">Position</th>\n')
    #webfile.write('\t\t<th style="font-size:30px">Observation</th>\n')
    #webfile.write('\t\t<th style="font-size:30px">Comments</th>\n')
    webfile.write('\t</tr>\n')

    for i in range(len(objcutouts)):
        if 'cutout1' in objcutouts[i]:
            
            webfile.write('\t<tr>\n')
            #webfile.write('\t\t<td style="text-align:center;font-size:30px" width=100% name="observation" title="'+objcutouts[i][8:-4]+'">'+objcutouts[i][8:-4]+'</td>\n')
            webfile.write('\t\t<td style="text-align:center;font-size:30px;vertical-align: middle" name="observation" title="'+objcutouts[i][8:-4]+'">'+objcutouts[i][8:-4]+'<br>\n')
            webfile.write('\t\t<input style="text-align:center;font-size:30px;vertical-align: middle" type="checkbox" name="quality'+objcutouts[i][8:-4]+'" value="quality1'+objcutouts[i][8:-4]+'">Bad Extraction\n')
            webfile.write('\t\t<input style="text-align:center;font-size:30px;vertical-align: middle" type="checkbox" name="quality'+objcutouts[i][8:-4]+'" value="quality3'+objcutouts[i][8:-4]+'">Flux Leak<br>\n')
            webfile.write('\t\t<input style="text-align:center;font-size:30px;vertical-align: middle" type="checkbox" name="quality'+objcutouts[i][8:-4]+'" value="quality5'+objcutouts[i][8:-4]+'">Poorly Subtracted Sky Lines\n')
            webfile.write('\t\t<input style="text-align:center;font-size:30px;vertical-align: middle" type="checkbox" name="quality'+objcutouts[i][8:-4]+'" value="quality6'+objcutouts[i][8:-4]+'">Bad Pixels\n')
            webfile.write('\t\t<input style="text-align:center;font-size:30px;vertical-align: middle" type="checkbox" name="quality'+objcutouts[i][8:-4]+'" value="Other'+objcutouts[i][8:-4]+'">Other<br>\n')
            webfile.write('\t\t<p style="font-size:15px;text-align:center; color:red">Do the issues significantly affect the signal of the object in the extraction window (between the green lines)?<br>If so, choose Major Issue; otherwise, choose Minor Issue. If there are no issues choose No Issue.<br></p>\n')
            webfile.write('\t\t<input style="vertical-align: 25%" type="radio" name="qualityradio'+objcutouts[i][8:-4]+'" value="No Issue">No Issue&nbsp;&nbsp;\n')
            webfile.write('\t\t<input style="vertical-align: 25%" type="radio" name="qualityradio'+objcutouts[i][8:-4]+'" value="Minor Issue">Minor Issue&nbsp;&nbsp;\n')
            webfile.write('\t\t<input style="vertical-align: 25%" type="radio" name="qualityradio'+objcutouts[i][8:-4]+'" value="Major Issue">Major Issue&nbsp;&nbsp;\n')
            webfile.write('\t\t</td>\n')

            webfile.write('\t</tr>\n')
            webfile.write('\t<tr>\n')
            #webfile.write('\t\t<td style="text-align:center" width=100% id="img'+str(i)+'" class="img"><img src="cutouts/'+str(object)+'/'+objcutouts[i]+'" width=1500pt>\n')
            #webfile.write('\t\t<td style="text-align:center" width=100% id="img'+str(i)+'" class="img"><img src="cutouts/'+str(object)+'/'+objcutouts[i]+'">\n')
            #webfile.write('\t\t<td style="text-align:center" width=100%><img src="cutouts/'+str(object)+'/'+objcutouts[i]+'" id="img'+str(i)+'" class="img">\n')
            webfile.write('\t\t<td><img src="'+relativedir+str(object)+'/cutout2_'+objbase[i]+'" id="img2_'+str(i)+'" class="img"></td>\n')
            webfile.write('\t</tr>\n')
            webfile.write('\t<tr>\n')
            webfile.write('\t\t<td><img src="'+relativedir+str(object)+'/cutout1_'+objbase[i]+'" id="img1_'+str(i)+'" class="img"></td>\n')
            
            
            webfile.write('\t\t<td class="pos" id="pos'+str(i)+'" style="text-align:left;width:25ch"></td>\n')
            webfile.write('\t</tr>\n')
            webfile.write('\t<tr>\n')
            webfile.write('\t<td colspan="2"><hr style="border-color:blue"><br><hr style="border-color:blue"></td>\n')
            webfile.write('\t</tr>\n')


    webfile.write('</table>\n')
            

    webfile.write('\t<h1 style="font-size:50px" clear=all>Coadded Spectrum</h1>\n')

    webfile.write('<table>\n')
    webfile.write('\t<tr>\n')
    webfile.write('\t\t<th style="font-size:30px">Coadd </th>\n')
    webfile.write('\t\t<th style="font-size:30px;width:10ch;text-align:left">Position</th>\n')
    webfile.write('\t</tr>\n')
    webfile.write('\t<tr>\n')
    webfile.write('\t\t<td style="text-align:center;font-size:30px;vertical-align: middle" name="coadd" title="coadd">\n')
    webfile.write('\t\t<input style="vertical-align: 25%" type="radio" name="qualityc" value="No Issue">No Issue&nbsp;&nbsp;\n')
    webfile.write('\t\t<input style="vertical-align: 25%" type="radio" name="qualityc" value="Maybe Issue">Maybe Issue&nbsp;&nbsp;\n')
    webfile.write('\t\t<input style="vertical-align: 25%" type="radio" name="qualityc" value="Definitely Issue">Definitely Issue&nbsp;&nbsp;\n')
    webfile.write('\t\t<input style="vertical-align: 25%" type="checkbox" name="qualitystar" value="Star">Star&nbsp;&nbsp;\n')
    webfile.write('\t\t</td>\n')
    webfile.write('\t</tr>\n')

    webfile.write('\t<tr>\n')
    webfile.write('<div id="container">\n')
    webfile.write('\t<td><img style="width:"+0.75*screen.availWidth src="'+relativedir+str(object)+'/coadd_smooth_'+str(object)+'.png" id="imgc" class="img" onclick="onCoaddClick(event)">\n')
    webfile.write('</div>\n')
    webfile.write('\t\t<td class="pos" id="posc" style="text-align:left;width:25ch"></td>\n')
    webfile.write('\t</tr>\n')
    webfile.write('\t<tr>\n')
    webfile.write('\t<td colspan="2"><hr style="border-color:blue"><br><hr style="border-color:blue"></td>\n')
    webfile.write('\t</tr>\n')
    webfile.write('\t<tr><td><center>\n')
    webfile.write('<div style="height:5em">\n')
    webfile.write('Number of Strong Emission Lines:&nbsp;<select id="numstrongemlines" onchange="changeLines(this)">\n')
    webfile.write('<option>0</option>\n')
    webfile.write('<option>1</option>\n')
    webfile.write('<option>2</option>\n')
    webfile.write('<option>3</option>\n')
    webfile.write('<option>&ge;4</option>\n')
    webfile.write('</select>&nbsp;\n')
    webfile.write('&nbsp;&nbsp;Their wavelengths (in &#8491;):&nbsp;<textarea style="vertical-align: text-top" id="strongemlines" name="stongemlines" style="font-size:20px" rows="1" cols="7"></textarea>&nbsp;&nbsp; ||| &nbsp;&nbsp\n')
    webfile.write('Number of Weak Emission Lines:&nbsp;<select id="numweakemlines" onchange="changeLines(this)">\n')
    webfile.write('<option>0</option>\n')
    webfile.write('<option>1</option>\n')
    webfile.write('<option>2</option>\n')
    webfile.write('<option>3</option>\n')
    webfile.write('<option>&ge;4</option>\n')
    webfile.write('</select>\n')
    webfile.write('&nbsp;&nbsp;Their wavelengths (in &#8491;):&nbsp;<textarea style="vertical-align: text-top" id="weakemlines" name="weakemlines" style="font-size:20px" rows="1" cols="7"></textarea>\n')
    webfile.write('</div></center></td>\n')
    webfile.write('</tr><tr><td><center>\n')
    webfile.write('\n')
    webfile.write('<div style="height:5em">\n')
    webfile.write('Number of Strong Absorption Features:&nbsp;<select id="numstrongabslines" onchange="changeLines(this)">\n')
    webfile.write('<option>0</option>\n')
    webfile.write('<option>1</option>\n')
    webfile.write('<option>2</option>\n')
    webfile.write('<option>3</option>\n')
    webfile.write('<option>&ge;4</option>\n')
    webfile.write('</select>&nbsp;&nbsp;\n')
    webfile.write('&nbsp;&nbsp;Their wavelengths (in &#8491;):&nbsp;<textarea style="vertical-align: text-top" id="strongabslines" name="stongabslines" style="font-size:20px" rows="1" cols="7"></textarea>&nbsp;&nbsp; ||| &nbsp;&nbsp;\n')
    webfile.write('Number of Weak Absorption Features:&nbsp;<select id="numweakabslines" onchange="changeLines(this)">\n')
    webfile.write('<option>0</option>\n')
    webfile.write('<option>1</option>\n')
    webfile.write('<option>2</option>\n')
    webfile.write('<option>3</option>\n')
    webfile.write('<option>&ge;4</option>\n')
    webfile.write('</select>&nbsp;\n')
    webfile.write('&nbsp;&nbsp;Their wavelengths (in &#8491;):&nbsp;<textarea style="vertical-align: text-top" id="weakabslines" name="weakabslines" style="font-size:20px" rows="1" cols="7"></textarea>\n')
    webfile.write('</div>\n')
    webfile.write('\n')
    webfile.write('</center></td></tr><tr><td><center>\n')
    webfile.write('Do the lines fit the data?&nbsp;\n')
    webfile.write('<input style="vertical-align: 25%" type="radio" name="specfit" value="Yes">Yes&nbsp;&nbsp;\n')
    webfile.write('<input style="vertical-align: 25%" type="radio" name="specfit" value="No">No&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n')
    webfile.write('Redshift Quality:&nbsp;\n')
    webfile.write('<select id="zquality">\n')
    webfile.write('<option></option>\n')
    webfile.write('<option>Wrong: Redshift does not fit lines</option>\n')
    webfile.write('<option>No Fit: No strong lines/&le;1 weak line</option>\n')
    webfile.write('<option>Maybe Fit: 1 strong line/2 weak lines</option>\n')
    webfile.write('<option>Likely Fit: 2 strong lines &amp; 1 weak line/&ge;2 weak lines</option>\n')
    webfile.write('<option>Definite Fit: &gt;2 strong lines</option>\n')
    webfile.write('</select>&nbsp;&nbsp;\n')
    webfile.write('Comments: <textarea style="vertical-align: middle" id="comments" name="comments" style="font-size:30px" rows="5" cols="30"></textarea><br><br>')
    webfile.write('\n')
    webfile.write('</center></td></tr>\n')
    webfile.write('<br>\n')
    webfile.write('<br>\n')
    webfile.write('\n')
    
    webfile.write('<td><center>\n')
    webfile.write('<button style="font-size:30px;vertical-align: text-top" onclick="downloadqualities(\'\', \'spec_qualities_'+str(object)+'.txt\', \'text/plain\')">Save Qualities</button></td>\n')
    webfile.write('</tr>\n')
#these two lines download and save the quality values
    #webfile.write('<button onclick="download(\'\', \'speccomments.txt\', \'text/plain\')">Click me</button>\n')
    webfile.write('</table>\n\n')
    webfile.write('</body>\n')

#this writes the javascript script to save the quality values to a text file
    webfile.write('<script>\n')
    webfile.write('\tfunction downloadqualities(text, name, type) {\n')
    #webfile.write('\t\tvar com = document.getElementsByName("comment");\n')
    webfile.write('\t\tvar obs = document.getElementsByName("observation");\n')
    #webfile.write('\t\tvar indquality = document.getElementsByName("observation");\n')
    webfile.write('\tinspectname = document.getElementById("inspectname");\n')
    webfile.write('\tvar texttosave = "Inspector: ";\n')
    webfile.write('\tvar qualityi = "";\n')
    webfile.write('\ttexttosave+=inspectname.value+"\\n";\n')
    webfile.write('\ttexttosave += "Object: ";\n')
    webfile.write('\ttexttosave+="'+str(object)+'\\n";\n')
    webfile.write('\ttexttosave += "zbest: ";\n')
    webfile.write('\ttexttosave+="'+str(zbest)+'\\n";\n')
    webfile.write('\t\ttexttosave += "Observation\tQuality\\n";\n')
    webfile.write('\t\tvar i;\n')
    
    webfile.write('\t\tfor (i=0; i < obs.length; i++) {\n')
    webfile.write('\t\t\tqualityi="";\n')

    
    #webfile.write('\t\t\ttexttosave+=String(obs[i].title)+"\t"+String(com[i].value)+" \\n";\n')
    webfile.write('\t\t\ttexttosave+=String(obs[i].title)+"\t";\n')

    webfile.write('\t\t\tqualityradio=document.getElementsByName("qualityradio"+obs[i].title);\n')
    webfile.write('\t\t\tif(qualityradio[0].checked) {\n')
    webfile.write('\t\t\t\ttexttosave+="No Issue";\n')
    webfile.write('\t\t\t} else if (qualityradio[1].checked) {\n')
    webfile.write('\t\t\t\ttexttosave+="Minor Issue";\n')
    webfile.write('\t\t\t} else if (qualityradio[2].checked) {\n')
    webfile.write('\t\t\t\ttexttosave+="Major Issue";\n')
    webfile.write('\t\t\t} else {\n')
    webfile.write('\t\t\ttexttosave+="No Quality";\n')
    webfile.write('\t\t\t}\n')
                      
    
    
    #webfile.write('\t\t\ttexttosave+=String(document.getElementsByName("quality"+String(i))[0].value+"\\n";\n')
    webfile.write('\t\t\tchecki=document.getElementsByName("quality"+obs[i].title);\n')
    webfile.write('\t\t\tif(checki[0].checked) {\n')
    webfile.write('\t\t\t\tqualityi+=", Bad Reduction";\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t\tif(checki[1].checked) {\n')
    webfile.write('\t\t\t\tqualityi+=", Flux Leak";\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t\tif(checki[2].checked) {\n')
    webfile.write('\t\t\t\tqualityi+=", Bad Sky Lines";\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t\tif(checki[3].checked) {\n')
    webfile.write('\t\t\t\tqualityi+=", Bad Pixels";\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t\tif(checki[4].checked) {\n')
    webfile.write('\t\t\t\tqualityi+=", Other";\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t\tif(!checki[0].checked && !checki[1].checked && !checki[2].checked && !checki[3].checked && !checki[4].checked) {\n')
    webfile.write('\t\t\t\tqualityi+=", No issue";\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t\ttexttosave+=qualityi+"\\n";\n')
    #webfile.write('\t\t\ttexttosave+=String(document.getElementsByName("quality"+obs[i].title)[1].checked)+"\\n";\n')
    webfile.write('\t\t}\n')
    webfile.write('\t\ttexttosave+="Coadd\t";\n')
    webfile.write('\t\tvar radioc=document.getElementsByName("qualityc");\n')
    webfile.write('\t\tif(radioc[0].checked) {\n')
    webfile.write('\t\t\ttexttosave+="No_Issue\\n";\n')
    webfile.write('\t\t} else if(radioc[1].checked) {\n')
    webfile.write('\t\t\ttexttosave+="Maybe_Issue\\n";\n')
    webfile.write('\t\t} else if(radioc[2].checked) {\n')
    webfile.write('\t\t\ttexttosave+="Definitely_issue\\n";\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\ttexttosave+="No_quality\\n";\n')
    webfile.write('\t\t}\n')

    webfile.write('\t\tvar starflag=document.getElementsByName("qualitystar");\n')
    webfile.write('\t\ttexttosave+="star_flag\t";\n')
    webfile.write('\t\tif(starflag[0].checked) {\n')
    webfile.write('\t\t\ttexttosave+="True\\n";\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\ttexttosave+="False\\n";\n')
    webfile.write('\t\t}\n')
    
    #webfile.write('\talert(document.getElementById("weakabslines").value);\n')
    webfile.write('\t\tvar stronge = document.getElementById("numstrongemlines");\n')
    webfile.write('\t\tvar numstrongelines = stronge.options[stronge.selectedIndex].text;\n')
    webfile.write('\t\tvar nstronge=numstrongelines[numstrongelines.length-1]+"\\n";\n')
    webfile.write('\t\tvar strongewaves=document.getElementById("strongemlines").value.replace(/\\n/g,", ");\n')
    webfile.write('\t\ttexttosave+="Number of Strong Emission Lines: "+nstronge;\n')
    webfile.write('\t\ttexttosave+="Strong Emission Line Wavelengths: "+strongewaves+"\\n";\n')
    
    webfile.write('\t\tvar weake = document.getElementById("numweakemlines");\n')
    webfile.write('\t\tvar numweakelines = stronge.options[weake.selectedIndex].text;\n')
    webfile.write('\t\tvar weakewaves=document.getElementById("weakemlines").value.replace(/\\n/g,", ");\n')
    webfile.write('\t\tvar nweake=numweakelines[numweakelines.length-1]+"\\n";\n')
    webfile.write('\t\ttexttosave+="Number of Weak Emission Lines: "+nweake;\n')
    webfile.write('\t\ttexttosave+="Weak Emission Line Wavelengths: "+weakewaves+"\\n";\n')
    
    webfile.write('\t\tvar stronga = document.getElementById("numstrongabslines");\n')
    webfile.write('\t\tvar numstrongalines = stronge.options[stronga.selectedIndex].text;\n')
    webfile.write('\t\tvar nstronga=numstrongalines[numstrongalines.length-1]+"\\n";\n')
    webfile.write('\t\tvar strongawaves=document.getElementById("strongabslines").value.replace(/\\n/g,", ");\n')
    webfile.write('\t\ttexttosave+="Number of Strong Absorption Features: "+nstronga;\n')
    webfile.write('\t\ttexttosave+="Strong Absorption Feature Wavelengths: "+strongawaves+"\\n";\n')

    webfile.write('\t\tvar weaka = document.getElementById("numweakabslines");\n')
    webfile.write('\t\tvar numweakalines = stronge.options[weaka.selectedIndex].text;\n')
    webfile.write('\t\tvar nweaka=numweakalines[numweakalines.length-1]+"\\n";\n')
    webfile.write('\t\tvar weakawaves=document.getElementById("weakabslines").value.replace(/\\n/g,", ");\n')
    webfile.write('\t\ttexttosave+="Number of Weak Absorption Features: "+nweaka;\n')
    webfile.write('\t\ttexttosave+="Weak Absorption Feature Wavelengths: "+weakawaves+"\\n";\n')

    webfile.write('\t\tradiofit=document.getElementsByName("specfit");\n')
    webfile.write('\t\ttexttosave+="OK fit?: "\n')
    webfile.write('\t\tif(radiofit[0].checked) {\n')
    webfile.write('\t\t\ttexttosave+="Y\\n";\n')
    webfile.write('\t\t} else if(radiofit[1].checked) {;\n')
    webfile.write('\t\t\ttexttosave+="N\\n";\n')
    webfile.write('\t\t} else {\n')
    webfile.write('\t\t\ttexttosave+="U\\n";\n')
    webfile.write('\t\t}\n')

    webfile.write('\tvar zq = document.getElementById("zquality");\n')

    webfile.write('\ttexttosave+="z quality: ";\n')
    webfile.write('\ttexttosave+=String(zq.selectedIndex-2)+"\\n";\n')

    
    webfile.write('\tcomments = document.getElementById("comments");\n')
    webfile.write('\ttexttosave+="Comments: ";\n')
    webfile.write('\ttexttosave+=comments.value+"\\n";\n')

    webfile.write('\t\tvar element = document.createElement("a");\n')
    webfile.write('\t\telement.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(texttosave));\n')
    webfile.write('\t\telement.setAttribute("download", name);\n')
    webfile.write('\t\telement.style.display = "none";\n')
    webfile.write('\t\tdocument.body.appendChild(element);\n')
    webfile.write('\t\telement.click();\n')
    webfile.write('\t\tdocument.body.removeChild(element);\n')
    
    webfile.write('\t}\n')

    
    webfile.write('</script>\n')




    
    webfile.write('<script>\n')
    
    webfile.write('\tfunction loadFileAsText() {\n')

    webfile.write('\t\tvar com = document.getElementsByName("comment");\n')
    webfile.write('\t\tvar obs = document.getElementsByName("observation");\n')
    #webfile.write('\t\tvar checkername = document.getElementsByName("Name");\n')
    #webfile.write('\t\tvar comments = document.getElementsByName("comment");\n')

    webfile.write('\t\tvar fileToLoad = document.getElementById("fileToLoad").files[0];\n')
    webfile.write('\t\tvar fileReader = new FileReader();\n')
    webfile.write('\t\tfileReader.onload = function(fileLoadedEvent){\n')
    webfile.write('\t\t\tvar textFromFileLoaded = fileLoadedEvent.target.result;\n')
    webfile.write('\t\t\tinputdata = textFromFileLoaded.split("\\n");\n')
    webfile.write('\t\t\tcheckername[0].value=inputdata[0];\n')
    webfile.write('\t\t\tvar i;\n')
    webfile.write('\t\t\tfor (i=1; i<inputdata.length; i++) {\n')
    webfile.write('\t\t\t\tif (inputdata[i].indexOf("Comment")!=-1) {\n')
    webfile.write('\t\t\t\t\tcomments[i-1].value=inputdata[i].substring(inputdata[i].indexOf("Comment"))\n')
    webfile.write('\t\t\t\t}\n')
    webfile.write('\t\t\t}\n')
    webfile.write('\t\t}\n')

    webfile.write('\t\tfileReader.readAsText(fileToLoad);\n')
    webfile.write('\t}\n')
    webfile.write('</script>\n')

    
    webfile.write('</body>\n')
    webfile.write('<script>\n')
    webfile.write('window.onload=function getWidth() {\n')
    webfile.write('\tvar tochange=document.getElementsByClassName("img");\n')
    webfile.write('\tvar i;\n')
    webfile.write('\tfor (i=0; i<tochange.length; i++) {\n')
    webfile.write('\t\ttochange[i].style.width = (0.75*window.outerWidth).toString()+"px";\n')
    webfile.write('\t\ttochange[i].style.height = "auto";\n')
    webfile.write('\t};\n')
    webfile.write('}\n')
    webfile.write('</script>\n')
    webfile.write('</html>\n')
    
    webfile.close()
    
